version: 2

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run: yarn
      - run: yarn test:generators
      - run: yarn test:flow
      - run: yarn test:lint
      - run: yarn test:render
      - run: yarn test:unit
      - run: yarn test:validate-xml

workflows:
  version: 2
  test-pr:
    jobs:
      - test
